### ISSUE TITLE
Add some illustrations 

### ISSUE THREAD

**Issue by flexbox** [MatthysDucrocq/GatsbySlides#1]
**Motivation**
After onboarded 100+ dev on my workshops, I noticed around 40% of them are visuals learners
![image](https://user-images.githubusercontent.com/360936/139399743-c3bdf796-2199-4b6c-b9c3-fea2aeeb4ce9.png)

_Try to explain everything to a 6 years old child with illustrations_

**Example:**

```
SSG - static site generation
```

![image](https://user-images.githubusercontent.com/360936/139399368-fbac67b0-a7ee-4bf4-9e14-5761924be1d9.png)

you can use 
- [x] https://excalidraw.com/
- [x] https://libraries.excalidraw.com/?target=_excalidraw&referrer=https%3A%2F%2Fexcalidraw.com%2F&useHash=true&token=nKKffQ1IIobjTvABsapjR&theme=light&sort=default

**Comment by MatthysDev** [comment]
Thanks for the review 🙏
updated
